src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $details;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $publish_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="image")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="book")
     */
    private $bookings;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(string $details): self
    {
        $this->details = $details;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(?\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

        /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;

/*         if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        } */
        
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBook($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBook() === $this) {
                $booking->setBook(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Book::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $book;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="date")
     */
    private $booking_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $return_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBookingDate(): ?\DateTimeInterface
    {
        return $this->booking_date;
    }

    public function setBookingDate(\DateTimeInterface $booking_date): self
    {
        $this->booking_date = $booking_date;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(\DateTimeInterface $return_date): self
    {
        $this->return_date = $return_date;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('details')
            ->add('publish_date', DateType::class, [
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy',
                'html5' => false
            ])
            ->add('category')
            ->add('imageFile', FileType::class,[
                'required' => false,
            ])
            ->add('author');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookingRepository;
use App\Repository\BookRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class BookController extends AbstractController
{

    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    /**
     * @Route("/books", name="books")
     */
    public function index(BookRepository $bookRepo): Response
    {
        $books = $bookRepo->findAll();
        return $this->render('book/index.html.twig', [
            'books' => $books,
        ]);
    }
    
        /**
     * @Route("/book/{id}", name="show_book")
     */
    public function getById(BookRepository $bookRepo, $id): Response
    {
        $book = $bookRepo->find($id);
        return $this->render('book/detail.html.twig', [
            'book' => $book,
        ]);
    }
    
    /**
     * @Route("/booking", name="booking")
     */
    public function getBooking(BookRepository $bookRepo, BookingRepository $bookingRepo): Response
    {

        $user = $this->security->getUser()/* ->getId() */;
        $bookings = $bookingRepo->findBy(['user' => $user], ['booking_date' => 'desc']);
/*        $books = [];
        foreach ($bookings as $booking) {
            $book = $booking->getbook();
            array_push($books, $book);
        } */
        
        return $this->render('book/booking.html.twig', [
            'bookings' => $bookings,
        ]); 
    }
    /**
     * @Route("/admin/add_book", name="add_book")
     * @Route("/admin/update_book/{id}", name="admin_update_book", methods={"GET","POST"})
     */
    public function addOrUpdateBook(Request $request, EntityManagerInterface $manager, Book $book = null): Response
    {

        if (!$book) {
            $book = new Book();
        }
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('imageFile')->getData();

            if ($image != null) {
                $fichier = md5(uniqid()).'.'.$image->guessExtension();
                // On copie le fichier dans le dossier uploads
/*                 $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                ); */
                $book->setImage($fichier);
            }
            $modif = $book->getId() !== null;
            $manager->persist($book);
            $this->addFlash("success", ($modif) ? "La modification a été effectuée" : "L'ajout a été effectuée");
            $manager->flush();
            return $this->redirectToRoute('manage_books');
        }

        return $this->render('admin/manage_book/edit_book.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
            'modif' => $book->getId() !== null
        ]);
    }
    /**
     * @Route("/admin/delete_book/{id}", name="admin_delete_book")
     */
    public function deleteBook(Request $request, EntityManagerInterface $manager, Book $book = null): Response
    {
        if($this->isCsrfTokenValid('SUP' . $book->getId(), $request->get('_token'))) {
            $manager->remove($book);
            $manager->flush();
            $this->addFlash("success", "La suppression a été effectuée");

            return $this->redirectToRoute('manage_books');
        }
    }
    /**
     * @Route("/admin/manage_books", name="manage_books")
     */
    public function manageBooks(BookRepository $bookRepo): Response
    {
        $books = $bookRepo->findAll();
        return $this->render('admin/manage_book/index.html.twig', [
            'books' => $books,
        ]);
    }
    
}

templates/book/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    img{
        margin-left: auto;
        margin-right: auto;
        margin-top: 15px;
        max-width: 150px;
        height: auto;
    }
    .max-card {
        max-width: 220px;
        height: auto;
    }
</style>

<br/>
    <h1>Livre(s) que vous avez emprunté(s)</h1>
    <br/>

        <br/>

        {% for msg in app.flashes("success") %}
            <div class="alert alert-success">
                {{ msg }}
            </div>
        {% endfor %}
        
        <br/>

    {% if bookings == [] %}
        <h5 class="card-title">Vous n'avez pas encore de réservation</h5>
    {% else %}
    <div class="card-deck">
        {% for booking in bookings %}
            <div class="card max-card" style="width: 18rem;">
                <img class="card-img-top" src="{{ asset('/images/books/'~ booking.book.image )}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{booking.book.title}}</h5>
                    <p class="card-text">{{booking.book.category}}</p>
                    {% if booking.returnDate != '' %}
                    <p class="card-text">Emprunté du : {{(booking.bookingDate|date('d-m-Y'))}} au : {{(booking.returnDate|date('d-m-Y'))}}</p>
                    {% else %}
                    <p class="card-text">Emprunté le : {{(booking.bookingDate|date('d-m-Y'))}}</p>
                    <p class="card-text">Ce livre est encore en votre possession. Il doit être rendu pour le : {{(booking.bookingDate|date_modify("+30 day")|date('d-m-Y'))}}</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

templates/book/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    img{
        margin-bottom: 15px;
        max-width: 150px;
        height: auto;
    }
</style>

<div class="example-wrapper">
<br/>
    <h1>Information sur : {{book.title}} </h1>
    <br/>
    <div class="card text-center">
        <div class="card-header">
            {{book.title}}
        </div>
        <div class="card-body">
            <img class="card-img-top" src="{{ asset('/images/books/'~ book.image )}}" alt="Card image cap">
            <h5 class="card-title">Autheur : {{book.author}}</h5>
            <p class="card-title">Catégorie: {{book.category}}</p>
            {% if book.publishDate != '' %}
                <h5 class="card-title">Date de publication: {{book.publishDate|date('Y')}}</h5>
            {% endif %}
            <p class="card-text"><i>{{book.details}}</i></p>
            <a href="{{ path('make_booking',{"id":book.id}) }}" class="btn btn-primary">Faire une réservation </a>
        </div>
    </div>

</div>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    img{
        margin-left: auto;
        margin-right: auto;
        margin-top: 15px;
        max-width: 150px;
        height: auto;
    }
    .max-card {
        max-width: 220px;
        height: auto;
    }
</style>

<br/>
    <h1>Liste des livres disponibles! ✅</h1>
    <br/>
    <div class="card-deck">
    {% for book in books %}
        <div class="card max-card" style="width: 18rem;">
            <img class="card-img-top" src="{{ asset('/images/books/'~ book.image )}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <p class="card-text">{{book.category}}</p>
                <a href="{{path("show_book",{"id":book.id}) }}" class="btn btn-primary">Voir le détail...</a>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}